server:
  port: 8081

# 应用名称
spring:
  application:
    name: sqlfilter

  datasource:
    url: jdbc:mysql:///demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1357zcbm#@!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #     配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      #     CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      #     最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      #     配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      #     设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #     设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #     可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #     保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

# 定义映射map
filter-query-builder:
  mapping:
    '[all]': 'and'
    '[any]': 'or'
    '[equals]': '='
    '[does not equal]': '!='
    '[is empty]': 'is null'
    '[is not empty]': 'is not null'
    '[contains]': 'like'
    '[does not contain]': 'not like'
    '[ends with]': 'like'
    '[begins with]': 'like'